### ISSUE TITLE
This sucks

### ISSUE THREAD

**Issue by louissypher800k** [EvixWasTaken/incelbot#1]
I'm sorry I wasted 20 minutes of my life downloading and running this. It just copies a recent comment and spits it back out. You said it worked in the readme. It doesn't work any better than a python scraper without AI. You should be ashamed of yourself.

**Comment by Fellythegrumpyboi** [comment]
skull

**Comment by PiotrChaberka** [comment]
This code is very old and deprecated. It worked when it was written, then i believe it was lightly edited and stopped working at some point. I might rewrite it somewhere in the future.
